vile:
  ignore: [
      "node_modules",
      ".test",
      "coverage"
    ]

length:
  config:
    file: 120
    line: 80

license:
  config:
    allowed: [
      "MPL",
      "MIT",
      "Public Domain",
      "PSF",
      "BSD",
      "Artistic",
      "ISC",
      "WTFPL",
      "Apache",
      "WTFPL",
      "GPL"
    ]

